### ISSUE TITLE
Full UX is unclear

### ISSUE THREAD

**Issue by estark37** [fedidcg/FedCM#10]
It sounds like there is some step that the browser is supposed to do to get the user's consent to share the user's IDP identity with the RDP. But it's unclear to me where that step is happening or what it might look like. I know that different browsers might want to design this UX differently, but perhaps you could sketch out some ideas of what this might look like to help readers visualize the full flow.

**Comment by npm1** [comment]
I don't think spec authors want to be prescriptive about user agent UI. @samuelgoto thoughts?

**Comment by samuelgoto** [comment]
> But it's unclear to me where that step is happening or what it might look like. 

Here one formulation that seems to be striking the right balance and a good baseline to start from:

![Screen Shot 2022-08-25 at 3 30 00 PM](https://user-images.githubusercontent.com/693738/186780019-abd24cfc-156b-4a33-b46b-79fad28971fe.png)

Does that help? Is this what you were looking for?

> I know that different browsers might want to design this UX differently, but perhaps you could sketch out some ideas of what this might look like to help readers visualize the full flow.

Right, different browsers can use different formulations. 

Like you suggested, this is left for each browser vendor to iterate and innovate, so not something that needs to go necessarily into the spec.

Closing this now, feel free to re-open if there is anything that we didn't quite capture in your comment.
