### ISSUE TITLE
Reference `referer` in id token endpoint?

### ISSUE THREAD

**Issue by dj2** [fedidcg/FedCM#114]
The example request for an idtoken has a `Referer` header field. This field is not listed in the required headers for the request.

The Revocation endpoint has a similar `Referer` header and has an explict mention that it's required - `with a Referer header indicating the RP URL`.

Is the Referer header required for the idtoken endpoint? If so, we should add it to the list of required headers.

**Comment by cbiesinger** [comment]
Is this now resolved by https://github.com/fedidcg/FedCM/pull/179 ?
