### ISSUE TITLE
Specify parameters to the RP logout endpoint.

### ISSUE THREAD

**Issue by dj2** [fedidcg/FedCM#116]
The logout endpoint [1] specifies a `GET` request but does not list any parameters passed in the request. At a minimum, is the `account_id` not required in order to log the user out?

1- https://wicg.github.io/FedCM/#logout_endpoint

**Comment by cbiesinger** [comment]
@dj2 why did you close this..?

**Comment by cbiesinger** [comment]
logoutRps has been removed from the spec.
