### ISSUE TITLE
Should FederatedCredentialRequestOptions only accept FederatedIdentityProviders?

### ISSUE THREAD

**Issue by dj2** [fedidcg/FedCM#117]
Currently the request options allows providers to be a `DOMString` or a `FederatedIdentityProvider`. It seems that most of our APIs require a `clientId` to function, but if `DOMString` is used there will be no client id provided.

```
partial dictionary FederatedCredentialRequestOptions {
  sequence<(DOMString or FederatedIdentityProvider)> providers;
};
```

Should the sequence be changed to just `FederatedIdentityProvider`? This would be a backwards incompatible change for the request options.

If we make that change, should the `protocol` field be moved into the request options as an optional field? This would make it clearer it's tied to the provider

**Comment by cbiesinger** [comment]
This has been fixed by the change to use IdentityCredential{,RequestOptions}

**Comment by cbiesinger** [comment]
https://fedidcg.github.io/FedCM/#dictdef-identitycredentialrequestoptions
