### ISSUE TITLE
Update `provider` in FederatedCredential?

### ISSUE THREAD

**Issue by dj2** [fedidcg/FedCM#118]
The `FederatedCredentialRequestOptions` can provide the provider as a `FederatedIdentityProvider` object. Currently the `FederatedCredential` has a   `readonly attribute USVString provider;` and `readonly attribute DOMString? protocol;`. Should the `provider` be `(USVString or FederatedIdentityProvider)` so things like the `client_id` and `nonce` are still available?

**Comment by cbiesinger** [comment]
We now use IdentityCredential, so this is not an issue anymore: https://fedidcg.github.io/FedCM/#identitycredential

We might want to add an idpConfigUrl property but that's largely orthogonal to this issue
