### ISSUE TITLE
Request FederatedCredential be removed from Credential Management Level 1 spec?

### ISSUE THREAD

**Issue by dj2** [fedidcg/FedCM#119]
We're working to build FedCM to be backwards compatible with the `FederatedCredential` in the Credential Management Level 1 spec. This means we have a few places where we can have a `DOMString or FederatedIdentityProvider` object. If we store the FederatedIdentityProvider object into the FederatedCredential as the `provider` then we have to make sure we have checks in the code for what type of value is in the variable. If it is a string we have to have separate logic to handle the requests.

This seems like, overall, a lot of duplicate work for something that is used very little in the wild currently. Would it be worthwhile requesting that the feature be removed from the Credential Management spec and the FedCM spec be the source of truth?

**Comment by yi-gu** [comment]
Close as obsolete since we didn't go with the `FederatedCredential` option.
