### ISSUE TITLE
Handling of name in accounts list response.

### ISSUE THREAD

**Issue by dj2** [fedidcg/FedCM#120]
Currently the accounts list response provides a `given_name` and `name` field where `name` is the full name and `given_name` is the first name(s).

These, almost, map to what Google Sign-in provides, with sign-in also providing a `family_name` field.

The OpenId Connect spec lists [6 different optional names](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims):

1. name
2. given_name
3. family_name
4. middle_name
5. nickname
6. preferred_username

How do we handle mappings for the names. If an IDP provides only `nickname` or `preferred_username` are they expected to be written into `given_name`?

The fields in the API are required, what happens if they are empty? What if the user did not provide a name to the IDP? Should they be optional?

Do we actually need multiple fields, or just a field for how we should refer to the user? The IDP then populates it with the information they have available that makes the most sense?

**Comment by yi-gu** [comment]
The FedCM spec should be protocol agnostic. To support showing more fields on the FedCM UI, we are [exploring](https://github.com/fedidcg/FedCM/issues/559#issuecomment-2057657128) the `Fields API`.

**Comment by TallTed** [comment]
> The OpenId Connect spec lists 6 different optional names 

This aspect of OIDC should be revisited, and we should not follow the examples described above.

See [Falsehoods about Names – With Examples](https://shinesolutions.com/2018/01/08/falsehoods-programmers-believe-about-names-with-examples/) and [much more](https://github.com/kdeldycke/awesome-falsehood).
