### ISSUE TITLE
Rational for having FederatedCredential.revoke(accountId) be a static method?

### ISSUE THREAD

**Issue by dj2** [fedidcg/FedCM#121]
The `revoke` method seems like it makes sense to call on the credential itself instead of as a static method. (Won't we also need things like the `provider` and `client_id` to make the call?

If feels like you're saying, I want to revoke this credential. But instead of saying that we're saying, hey revoke stuff for this `account_id` which seems like it's up a level?

**Comment by cbiesinger** [comment]
https://github.com/WICG/FedCM/pull/139

Please take a look!

**Comment by dj2** [comment]
`revoke` is no-longer a `static`. Closing.
