### ISSUE TITLE
Return value if no account found when calling accounts_endpoint?

### ISSUE THREAD

**Issue by dj2** [fedidcg/FedCM#124]
If the IDP attempts to find a user account, and for some reason comes up empty, does the [accounts_endpoint](https://wicg.github.io/FedCM/#accounts_endpoint) return a `404`, or an empty JS array for accounts?

```javascript
{
  accounts: []
}
```

**Comment by cbiesinger** [comment]
- With regards to what an IDP should do, empty array probably makes more sense but from our perspective we treat it all the same way
- With regards to signup_url (now login_url), we have now explicit text in the spec that define it

**Comment by cbiesinger** [comment]
closing accordingly
