### ISSUE TITLE
What happens during `sign-up` if user rejects?

### ISSUE THREAD

**Issue by dj2** [fedidcg/FedCM#128]
In the signup flow the user has to consent to creating an account, agree to ToS and privacy. What does the algorithm return if the user does not consent?

**Comment by samuelgoto** [comment]
Ah, good question, this isn't specified yet, but it is implemented: it rejects the promise (or resolves the promise with a `false` value), I believe.

**Comment by cbiesinger** [comment]
This is now specified as part of the request permission algorithm: https://fedidcg.github.io/FedCM/#request-permission-to-sign-up
