### ISSUE TITLE
Does user consent to specific data being shared?

### ISSUE THREAD

**Issue by dj2** [fedidcg/FedCM#129]
During the `sign-up` algorithm the user consents to creating an account. Does this consent form show what data is being shared (name, email, etc) or is it a general consent?

Does the user get notified what data will be shared?

**Comment by samuelgoto** [comment]
> During the sign-up algorithm the user consents to creating an account. Does this consent form show what data is being shared (name, email, etc) or is it a general consent?

The spec leaves that open for each user agent to form an opinion on how to transparently explain that to a user. 

I personally like the analogy of the "TLS certificate inspector" that chromium has, which gives a "high level explanation" but also has the ability for the user to see the entirety of the data, but again, I think each user agent should be left to decide how to serve their users better.

<img width="1552" alt="Screen Shot 2021-11-03 at 9 52 10 AM" src="https://user-images.githubusercontent.com/693738/140110195-b7c69218-6be1-4d37-928d-97d174f85aec.png">

<img width="1552" alt="Screen Shot 2021-11-03 at 9 52 18 AM" src="https://user-images.githubusercontent.com/693738/140110389-25ba0bcc-c012-41ac-a34b-a4e9b7b7d813.png">


> Does the user get notified what data will be shared?

**Comment by cbiesinger** [comment]
We now show the specific data being shared in the permissions prompt and #559 will let RPs customize this, so I think we can close this.
