### ISSUE TITLE
Example 20 is inconsistent with IDL definitions

### ISSUE THREAD

**Issue by cbiesinger** [fedidcg/FedCM#138]
https://wicg.github.io/FedCM/#browser-api-idp-sign-in

```
  const credential = new FederatedCredential({
    id: id,
    provider: 'https://idp.example',
    name: name,
    iconURL: iconUrl,
    client_id: "1234",
  });
```

But FederatedCredential does not have a client_id field:
https://wicg.github.io/FedCM/#idl-index
https://w3c.github.io/webappsec-credential-management/#federatedcredential
https://w3c.github.io/webappsec-credential-management/#credential

https://w3c.github.io/webappsec-credential-management/#credentialuserdata

**Comment by cbiesinger** [comment]
Additionally, FedCM really should add idToken and approvedBy to FederatedCredentialInit, though that won't make a difference for this example.

**Comment by cbiesinger** [comment]
@dj2 fyi

**Comment by dj2** [comment]
There is currently a mis-match in the spec. I think that example should pass a `FederatedIdentityProvider` instead of the `provider` string. The provider string is what's in the Credential Mangement FederatedCredential but we over-ride it to make it `string | FederatedIdentityProvider`. Then `client_id` would move into that object.

I think? Would have to check the IDL a bit more to know if there are other changes needed.

**Comment by cbiesinger** [comment]
> we over-ride it to make it string | FederatedIdentityProvider

Where do we do that...? I only see it in FederatedCredentialRequestOptions, not in FederatedCredential or FederatedCredentialInit

**Comment by dj2** [comment]
Oh, we did it in the RequestOptions only. I think we _also_ need to do it in FederatedCredential. My preference would be to just remove the `string` option as do we want to support that? My guess it was left off of `FederatedCredential` as the current spec doesn't technically return a `credential` object we just return the `idToken` so...why add it. But we want it now, heh, and hopefully will evolve the spec such that we're returning the credential object.

I think both init and credential should store the FederatedIdentityProvider.

(I also wonder if our `FederatedIdentityProvider` should have a `protocol` string in it as the CredentialManagement FederatedCredential has.

**Comment by dj2** [comment]
@cbiesinger can this be closed with the new API updates?

**Comment by samuelgoto** [comment]
I think this problem goes away when [this](https://github.com/fedidcg/FedCM/pull/207) gets merged.

**Comment by cbiesinger** [comment]
The initial issue is fixed but not this one:

> Additionally, FedCM really should add idToken and approvedBy to FederatedCredentialInit, though that won't make a difference for this example.

**Comment by dj2** [comment]
Neither of those things exist on FederatedCredential anymore.

**Comment by cbiesinger** [comment]
sorry, yes, you're right.

Should we make provider a FederatedIdentityProvider though? (on FederatedCredential and *Init)

**Comment by dj2** [comment]
We don't actually specify anything on `FederatedCredential` at the moment. I think we should probably add that into this spec and kick off the request to remove from Credential Management Level 1 if possible.

**Comment by cbiesinger** [comment]
The spec no longer has an example like the one in here, so closing this as obsolete.
