### ISSUE TITLE
Origin validation

### ISSUE THREAD

**Issue by dj2** [fedidcg/FedCM#146]
The `FederatedCredential` object is `origin bound`. The `FederatedCredentialInit` object has a required `origin` parameter which is the origin the credential is to be bound too. When we call `navigator.credentials.store` on the federate credential what validation do we need to do on the origin?

I believe the original idea was that an IDP could store the credential for an RP. But, if the store call is available does that mean an RP could store the credential for a separate RP? Could site1.com store the credential they just received with a store origin of site2.com?

The store text for a FederatedCredential will need to be setup in such a way that it will ask permission when required. If I call `get` and receive a credential back and immediately call `store`, the user should not be prompted as we've already prompted for that credential. But, if I create a FederatedCredential object and call `store`, then we need to prompt the user for authorization?

**Comment by dj2** [comment]
What are the security and privacy implications of allowing one origin to set context for a different origin which may not even know it's being set?

**Comment by pkotwicz** [comment]
#147 has a lot of related context

**Comment by dj2** [comment]
I think there are a few distinct parts to this:

# Seperate origin
> I have a top-level origin of `IDP.example.com`, can I set a credentail to RP.test.com?

In this case we'd prompt the user with some thing like `Sign in to RP.test.com with IDP.example.com` which would potentially be confusing given the user is on `IDP.example.com`. Why are they getting prompted to allow `RP.test.com` to sign-in?

# IFrames
This boils down to what does it mean to make a FedCM call inside an iframe. The current spec requires 
`sameAncestorsAsOrigin` to be `true` or the `get` fails. This means we'd only allow the credential to be returned if every iframe and the top-level context are `same-origin`. This seems more restrictive then we desire, as, I think, it means we can't have an iframe with the IDP set the credential for the embedding RP.

> I have a top-level origin of `[RP.test.com [iframe IDP.example.com]]`. Can IDP.example.com set the credential for RP.test.com

This would currently be rejected as the origins don't match, but I think we want it to work. `Sign-in to RP with IDP`. So, the IDP iframe could `credential.store` with an origin of `rp.test.com`.


> I have a top-level origin of `[RP.test.com [iframe Foo.com [iframe IDP.example.com]]` . Can IDP set a credential for foo.com, rp.test.com or neither?

This becomes a bit more interesting. It's `foo.com` that is authenticating. So, we'd end up prompting `Sign-in to Foo with IDP` which is a little strange when you're on the RP website. You would get this prompt even if  you're already signed into RP. So, you would be required to authenticate multiple times. If allowed, this would store the credential so `foo.com` could retrieve it, but not `rp.com`.


> I have a top-level origin of `[RP.example.com [iframe IDP.example.com]]`. 

These are already `sameOriginWithAncestor` so IDP can store the credential for RP now.


> I have a first-party-set of `[RP.test.com, IDP.example.com]` and a page with `[RP.test.com [iframe IDP.example.com]]`. Can IDP set a credential for RP in this case?

This seems like a logical extension of the origin set where we extend `sameOriginWithAncestor` to `sameFirstPartySetWithAncestor`. 


> I have a first-party-set of `[RP.test.com, IDP.example.com]` and a page with `[RP.test.com [iframe Foo.com [iframe IDP.example.com]]]`. Can IDP set a credential for foo.com, rp.test.com or neither?

This seems like the same case as the non-fps above that is similar. It stores into Foo.com, not RP.test.com.


> I have a first-party-set of `[RP.test.com, IDP.example.com]` and a page with `[Foo.com [iframe RP.test.com [iframe IDP.example.com]]]`. Can IDP set a credential for foo.com, rp.test.com or neither?

Similar, how the messaging works could be the confusing part.

# Where is the credential visible?
This all has a knock on question of, if I visit `[RP.example [iframe foo.com [iframe login.idp]]]` and we were to say that the inner `login.idp` sets the credential to `foo.com`. If I then visit `foo.com` directly, is that credential visible? Or, is that credential tied the `[RP.example, foo.com]` pair? The opposite is also a question, I visit `foo.com` and then visit `[RP.example [iframe foo.com [iframe login.idp]]]` do we provide the credential access?

As a user, are you authenticating `foo.com` or are you authenticating `foo.com` in the context of `RP.example`?

I guess the question is, does your identity get partitioned by the top level set?

**Comment by pkotwicz** [comment]
Scenario 1:
My understanding is that we want to intentionally break this scenario because it is explicitly called out in the CHIPS design doc https://github.com/WICG/CHIPS#third-party-customer-service-chat-embed
User signs into `[rp1.com [iframe chat.com [iframe login.idp]]`
User visits `[rp2.com [iframe chat.com [iframe login.idp]]`
  User should not be signed into chat.com on rp2.com

Scenario 2:
User signs into `[rp1.com [iframe chat.com [iframe login.idp]]]`
User visits `[chat.com [iframe login.idp]]`

My preference is for the user to be signed into the toplevel chat.com frame in addition to the chat.com iframe.

Scenario 3:
Page `[aggregator.com [iframe rp1.com [iframe idp1.com]]
                                     [iframe rp2.com [iframe idp2.com]]
          ]`
User signs into RP rp1.com with IDP idp1.com

Stored credential can only be obtained from rp1.com and idp1.com
Stored credential cannot be obtained by aggregator.com, rp2.com, idp2.com

**Comment by dj2** [comment]
For your Scenario 3. _A_ credential could be retrieved for _aggregator.com_ but it would be a different credential from (rp1.com, idp1.com)

**Comment by dj2** [comment]
Yes, I believe your scenario 1 should not have access to the credential or the cookie as the top level origin are different.

I'm not sure I'm convinced your scenario 2 should work as the context is different. Visiting chat.com is different from an embedded chat.com inside of rp1.com

**Comment by yi-gu** [comment]
Close as obsolete since we are not using FederataedCredential or n.c.store in the FedCM API.
