### ISSUE TITLE
[VK Company Feedback] OneTap widgets

### ISSUE THREAD

**Issue by NekR** [fedidcg/FedCM#148]
Hello!

I saw a few mentions of OneTap widgets in the docs, but wasn't able to found proposals about it.
Closest thing I saw is this mock for Mediation-oriented API: https://github.com/WICG/FedCM/blob/main/explainer/static/mock40.gif
It looks just like OneTap on mobile. Is it meant to be exactly that and if so, what would be it's UI on desktop?

**Comment by dj2** [comment]
The OneTap widget is an existing widget. You can see more information about it on https://developers.google.com/identity/gsi/web. There is also a use case with the FedIDCG which details some more information and provides links to examples: https://github.com/fedidcg/use-case-library/issues/12

**Comment by NekR** [comment]
> The OneTap widget is an existing widget. You can see more information about it on https://developers.google.com/identity/gsi/web.

That's a widget from Google. We're looking into continue having our OneTap widgets working properly once third-party cookie are gone.

> There is also a use case with the FedIDCG which details some more information and provides links to examples: fedidcg/use-case-library#12

Can you please help navigate me to the best place to provide feedback about OneTap widgets (them being gone with third-party cookie, them being needed after that fact, etc.)? Maybe it's that issue or maybe we better continue here.

**Comment by dj2** [comment]
Sorry, I provided the Google example as that's the OneTap widget I know. If you have a separate one, and can share what it is, we'd love to hear about it.

The first step for the OneTap question is, does the use case I linked above match up to how your OneTap widget works? We believe it's correct, and it matches the Google case, but if it doesn't match your case can you please add comments as to what is different / won't work? We're working off the use case to determine if our mediation flow will work correctly. Any feedback on the use cases (or if you want to file new issues with the FedID-CG listing other use cases) would be greatly appreciated.

Our mediation flow, and the API you can see in #145 is, we think, sufficient for OneTap widgets to continue to function post third-party cookie deprecation. We're working on updating Chrome to use the new API, it's currently on an older version of the API that didn't follow the Credential Management API spec as the new one does.

**Comment by samuelgoto** [comment]
> We're looking into continue having our OneTap widgets working properly once third-party cookie are gone.

Ah, interesting! Could you share with us a link of how yours work?

**Comment by NekR** [comment]
> The first step for the OneTap question is, does the use case I linked above match up to how your OneTap widget works?

In more general use case, yes. But there are details which should be covered to understand if it works for all the cases.
I wrote some questions here: https://github.com/fedidcg/use-case-library/issues/12

> Our mediation flow, and the API you can see in https://github.com/fedidcg/FedCM/issues/145 is, we think, sufficient for OneTap widgets to continue to function post third-party cookie deprecation.

As far as I understand, it covers only "popover over website" OneTap case, but there are cases for inline/in-markup OneTap, basically what is done with <iframe> nowdays. Demo here:  https://youtu.be/sbCU12GrMP8 and on the picture below.

Also, the "OneTap" in some cases may need to open a "popup" to the user with additional UI: scopes, additional registration steps user needs to finish, e.g. website integrating OneTap requires phone number but user haven't specified it yet, etc. Right now there are several ways to open such UI: a new window popup, e.g. window.open(), a new tab popup (window.open() too) and current tab navigation. With the built-in browser UI involved, I suppose a native popup over current page might be enough, but sometimes for people who integrate the "OneTap" and IDP Auth in general -- a redirect on current page is more friendly. I do not remember exact details, but it maybe something like "all other our system work that way already" and "we do not want this data to showup in JavaScript, but rather directly on backend".
Demo of opening a popup from OneTap is also on the video above.

> Ah, interesting! Could you share with us a link of how yours work?

Better! A screenshot :) (and the video above)
<img width="1115" alt="Screenshot 2022-02-11 at 17 08 15" src="https://user-images.githubusercontent.com/1189265/153752676-54dbf37c-905d-4a3a-af4c-353283477258.png">

P.S.
I also left my feedback here https://github.com/fedidcg/use-case-library/issues/10#issuecomment-1037994883, since it seems relevant.

**Comment by samuelgoto** [comment]
Oh, that does look like a good candidate for the account chooser that we built!

@NekR any chance you could hop into one of the FedID CG calls to walk us through how your product works?

**Comment by NekR** [comment]
@samuelgoto yeah, sure. Where should I start to get there?

**Comment by samuelgoto** [comment]
@hlflanagan would know best, but I think it involves:

1) joining the FedID CG by clicking [here](https://www.w3.org/community/fed-id/)
2) getting yourself into the agenda of one of the meetings in this [schedule](https://github.com/fedidcg/meetings)

Any chance that would work?

**Comment by hlflanagan** [comment]
After you join, I can send you the Slack invite, too.

**Comment by tttzach** [comment]
Closing this issue for now. Feel free to file a new issue or hop on a FedIDCG call with us whenever you're ready.
