### ISSUE TITLE
Intent to Migrate: FedCM to Federated Identity CG

### ISSUE THREAD

**Issue by timcappalli** [fedidcg/FedCM#161]
### Working group decision to adopt

This is moving to another community group as a work item, not a working group for adoption.

Work item decision: https://github.com/fedidcg/meetings/blob/main/2021/2021-12-03-notes.md

### Proposal

Proposed CG work item: https://github.com/fedidcg/proposals/issues/1

### Motivation and Use Cases

The Federated Identity CG is a focused community group on federated identity where this proposal has more eyes in the identity community.

### Compatibility Risk

n/a, this is simply a CG to CG transfer

### Ongoing technical constraints

n/a, this is simply a CG to CG transfer

### Link to implementation experience and demos

n/a, this is simply a CG to CG transfer

### Data

n/a, this is simply a CG to CG transfer

### Security and Privacy

n/a, this is simply a CG to CG transfer

### Accessibility

n/a, this is simply a CG to CG transfer

### Internationalization

n/a, this is simply a CG to CG transfer

**Comment by samuelgoto** [comment]
I'm supportive of this move. 

We will find more identity specific domain experts at FedID CG than WICG, increasing our chances of designing the right things. 

It seems like a natural, incremental and desired progressions from the WICG, who has welcomed/served us well so far but we feel like we may be outgrowing it.

So,  +1 from where I stand.

**Comment by travisleithead** [comment]
This move has been completed: https://github.com/fedidcg/FedCM

**Comment by samuelgoto** [comment]
Neat! Resolving this issue!
