### ISSUE TITLE
Missing IPR check?

### ISSUE THREAD

**Issue by dj2** [fedidcg/FedCM#167]
In the WICG repo pull requests would do an IPR check for each pull. That doesn't seem to happen after the repo transfer?

**Comment by dj2** [comment]
@tidoust would you be able to point me in the right direction to get the IPR bot up and running after we moved from WICG/FedCM to fedidcg/FedCM?

**Comment by tidoust** [comment]
New organizations need to be added manually to the [repo manager](https://labs.w3.org/repo-manager/). I don't think I can do that myself but I believe @deniak is on it.

**Comment by deniak** [comment]
I'll take care of adding that repository to the repo manager but I'll need to be invited as an **owner** of the fedidcg org to:
1. grant @w3cbot access to the org
2. import the repository with the necessary privileges

@timcappalli, can you please send me an invite?

**Comment by deniak** [comment]
`fedidcg/FedCM` has been imported into the repository manager. All the PRs to that repo will now go throught the IPR check. Let me know if other repositories should also be imported.

**Comment by dj2** [comment]
Perfect. Thanks everyone for all the help.
