### ISSUE TITLE
Document auto-signin API

### ISSUE THREAD

**Issue by cbiesinger** [fedidcg/FedCM#172]
In Chrome we have a prototype for the auto-signin API:
https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/credentialmanager/federated_credential_request_options.idl;l=15?q=preferAutoSignin%20-file:gen&ss=chromium

We should add it to the spec.

@yi-gu

**Comment by dj2** [comment]
Tracking the usage back the flag passed by the RP eventually triggers the following in Chrome:  https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/android/webid/internal/java/src/org/chromium/chrome/browser/ui/android/webid/AccountSelectionMediator.java;l=221;drc=91318efd060e4164810264f47cd31b3fc7159d68;bpv=1;bpt=1

Which changes the user confirmation dialog from having a `continue` button to having a `cancel` button and an auto-submit timer.

Is that the current behaviour?

In terms of the spec, does `preferAutoSignin` have to be honoured or is it hint to the browser?

**Comment by cbiesinger** [comment]
I believe it's a hint, but I defer to @yi-gu on that question

**Comment by yi-gu** [comment]
It's a hint. Auto sign-in is determined by several factors such as `preferAutoSignin` from RP, availability from IDP, opt-out status from users etc..

**Comment by tttzach** [comment]
This is now part of the spec, it is the mediation parameter of CredentialRequestOptions https://w3c.github.io/webappsec-credential-management/#dom-credentialrequestoptions-mediation.
