### ISSUE TITLE
Find a better solution for feature detection

### ISSUE THREAD

**Issue by cbiesinger** [fedidcg/FedCM#180]
currently you have to do `if ('FederatedCredential' in window && 'revoke' in FederatedCredential)`, it would be nice if there was a more direct way.

**Comment by samuelgoto** [comment]
The other option that Jeremy suggested was something along the lines of:

```js
function isFedCMSupported() {
  let supported = false;
  navigator.credentials.get({mediation: "silent", signal: AbortSignal.abort(), federated: {get providers() { supported = true; return []; }}}).catch(() => {});
  return supported;
}
```

None of these are wonderful, but I think I got some confirmation that there isn't anything more obvious/better that we could do, which I think settles this issue: isn't (arguably) a *better* solution to feature detection, there is an alternative (above) which we expect to work equally well.

I'll update the HOWTO.md to match this suggestion and I'll let devrels to decide what's the best of the two non-wonderful alternatives :)
