### ISSUE TITLE
Change value of Sec-FedCM-CSRF

### ISSUE THREAD

**Issue by bvandersloot-mozilla** [fedidcg/FedCM#187]
The IDP only checks whether or not this header exists. However, a client could mistakenly (and not technically incorrectly) send the same value with all requests. I suggest we remove this foot-gun and use a fixed value for this header. This is done in other secure headers, such as `[Sec-Fetch-User](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-User)`.

**Comment by samuelgoto** [comment]
Ah, that's an interesting suggestion. That seems safer indeed and I don't think it would not meet any of the goals of having it (i.e. which is to have the IDP the ability to know that this wasn't generated via the JS content area).

Thanks, that seems reasonable to me!

I'll add this to my queue and get to it at some point, but in case you have the inclination, feel free to send a PR to the spec and I'll merge.

**Comment by samuelgoto** [comment]
@dj2 @cbiesinger FYI
