### ISSUE TITLE
Define HTTP requests in terms of fetch

### ISSUE THREAD

**Issue by cbiesinger** [fedidcg/FedCM#188]
As described in https://chromium-review.googlesource.com/c/chromium/src/+/3440497/comments/94effc8e_e20237c0, we should define the HTTP requests in terms of fetch to get the correct semantics.

**Comment by cbiesinger** [comment]
note to self, https://fetch.spec.whatwg.org/#requests

**Comment by samuelgoto** [comment]
Resolving this as a duplicate of:

https://github.com/fedidcg/FedCM/issues/261
