### ISSUE TITLE
Spec should not talk about auto signin

### ISSUE THREAD

**Issue by cbiesinger** [fedidcg/FedCM#210]
https://fedidcg.github.io/FedCM/#create-credential

> To create-credential run this algorithm:
> [...]
> 6. Return the result of running the [auto sign-in](https://fedidcg.github.io/FedCM/#auto-sign-in) algorithm.

But this should still get explicit consent from the user and not auto signin them.

**Comment by tttzach** [comment]
Create credential is no longer in the spec and auto signin is now the mediation parameter of CredentialRequestOptions https://w3c.github.io/webappsec-credential-management/#dom-credentialrequestoptions-mediation.
