### ISSUE TITLE
Clarify the manifest URLs

### ISSUE THREAD

**Issue by dj2** [fedidcg/FedCM#216]
The manifest URLs can either be absolute or they're relative to the `url` provided in the `get` request. This should be clarified and spelled out in the spec.

**Comment by cbiesinger** [comment]
I would prefer that we write it as "relative to the manifest file"

**Comment by agektmr** [comment]
Does this mean If the manifest is at `https://idp.example/something/fedcm.json`, can you do something like `../accounts_list` to point to `https://idp.example/accounts_list`?

**Comment by agektmr** [comment]
I mean, you can of course do `/accounts_list` to indicate starting from root, but what if it's deeper? can you use `../` to point to the parent path?

**Comment by npm1** [comment]
We currently use the https://fedidcg.github.io/FedCM/#parse-url algorithm
