### ISSUE TITLE
Clarify and specify the client id's returned as part of the account list

### ISSUE THREAD

**Issue by dj2** [fedidcg/FedCM#217]
The account list can provide a set of client id's the account is registered with. This should be clarified that it's an optional hint to the browser when displaying the terms of service and the privacy policy.

It should also be made clear that since the client_id is not sent to the account_list request, this is a list of _all_ RPs and can't be filtered to just the current RP.

**Comment by yi-gu** [comment]
This is addressed in https://fedidcg.github.io/FedCM/#dom-identityprovideraccount-approved_clients and https://fedidcg.github.io/FedCM/#network-requests
