### ISSUE TITLE
`revoke()` should take a `hint` that is independent from the `accountId`

### ISSUE THREAD

**Issue by samuelgoto** [fedidcg/FedCM#229]
The revocation endpoint takes "hints" that are different than the "account_id" that it passed to FedCM during the "accounts_endpoint". So, I think we should expose some form of parameter in the revoke method to allow that to be passed to the HTTP endpoint.

Here is a draft of what I was imagining, but open to any other formulation that allows this to be done:

```js
const cred = await navigator.credentials.get({
  federated: {
    providers: [{
      url: "idp.example",
      clientId: "123",
      // no hint needed here, see below
    }]
  }
});
cred.revoke({
  hint: "user@google.com"
})
```

**Comment by dj2** [comment]
Just to note the `get` hint _maybe_ needed if this is a multi-account situation.
