### ISSUE TITLE
Updates to privacy policy and terms of service

### ISSUE THREAD

**Issue by dickhardt** [fedidcg/FedCM#247]
Today, RPs need to track which ToS and PP a user has agreed to in order to prompt them when the ToS / PP are updated. Most RPs are challenged in doing this.

It is easier for the IdP to track which terms a given user has already agreed to, and we have an opportunity here for the IdP to signal to the UA that terms have changed and get explicit agreement to the new terms.

**Comment by dickhardt** [comment]
Somehow I overlooked that API --  it is not clear to me what is included in a client being "approved" -- and the field is optional => so not a clear indicator of ToS and PP. If that is what it is for, perhaps we can call it something that indicates the user has consented to the terms?

**Comment by samuelgoto** [comment]
>  it is not clear to me what is included in a client being "approved"

It is a list of client ids. example:

```json
{
 "accounts": [{
   "id": "1234",
   "given_name": "John",
   "name": "John Doe",
   "email": "john_doe@idp.example",
   "picture": "https://idp.example/profile/123",
   "approved_clients": ["123", "456", "789"]
  }, {
   "id": "5678",
   "given_name": "Johnny",
   "name": "Johnny",
   "email": "johnny@idp.example",
   "picture": "https://idp.example/profile/456"
   "approved_clients": ["abc", "def", "ghi"]
  }]
}
```

> and the field is optional => so not a clear indicator of ToS and PP.

It indicates whether the IDP wants the browser to show the ToS and the PP.

I sent a PR to be more precise about how we are using the `approved_clients` field:

https://github.com/fedidcg/FedCM/pull/270

>  If that is what it is for, perhaps we can call it something that indicates the user has consented to the terms?

Yeah, agreed that the name is a bit off. 

Does it do what you want to it to do though?

If so, suggestions for better names?

**Comment by npm1** [comment]
No response on this one so closing but feel free to comment if you want it reopened
