### ISSUE TITLE
Missing states in state machine 9.1

### ISSUE THREAD

**Issue by dickhardt** [fedidcg/FedCM#249]
https://fedidcg.github.io/FedCM/#browser-api-state-machine

The state mention shows the state that the relationship has been revoked. One assumes this is the relationship between the RP, the user, and the IdP. What about the user's relationship with the IdP?

The user has an account at the IdP or not. There is no API for the IdP to tell the browser the user has an account at the IdP -- this seems to be implied by the IdP setting cookies -- but cookies can be cleared -- and having an account at an IdP would be something that the user may want the browser to sync across devices. 

There are also the various states with the IdP and the user / browser. Logged out of IdP, Logged into IdP. and a spectrum of confidence the IdP has that the user is still controlling the device.

OpenID Connect and some IdPs now support ACR to indicate the authentication "strength" the IdP has of the user. How will the RP request this in the API, and how with the browser request this of the IdP, and how will the process be stepped up?

**Comment by npm1** [comment]
The state machine has been reworked. Can you take a look and see if it makes more sense now? But you are right that right now we use credentialed requests to the IdP to request the user accounts. So if there are no cookies then the list returned would presumably be empty.

**Comment by npm1** [comment]
We haven't heard back so I'm going to close this but let us know if you still think that there are issues with the algorithms.
