### ISSUE TITLE
ID Token verification API?

### ISSUE THREAD

**Issue by dickhardt** [fedidcg/FedCM#250]
Why not wrap the crypto.subtle verification APIs to retrieve the IdP jwks file and verifiy the ID Token given the browser now has the context of ID Tokens>?

**Comment by timcappalli** [comment]
@dickhardt the browser should be treating tokens as opaque strings. What benefit does the browser checking a token's signature bring? The RP still needs to validate it.

**Comment by vibronet** [comment]
It's not just a matter of format, tho. We created a profile for access tokens to use a well known JWT based encoding, but the RFC is still very clear about that not being license for an entity that isn't the intended recipient to look into tokens, see https://www.rfc-editor.org/rfc/rfc9068.html#name-security-considerations
The ID token has a format, but it's still meant for the client and intermediaries trying to intercept it might find it encrypted, devoid of user attributes if requested with any `response_type` other than `id_token`, or the client might decide to use custom validation logic (family of clientIDs, tolerance of expired tokens within a certain threshold to handle outrages gracefully, etc etc).
Unless the ID token `aud` is actually the browser (and in that case it shouldn't be used to access an RP), the browser shouldn't look into it or risk seeing its logic break if something changes, possibly without remediation.

**Comment by vibronet** [comment]
I referred to an access token because you yourself pitted IDtokens vs oauth tokens, and mentioned the fact that the format of an IDtoken is known as license for an intermediary to look inside it. I presented a case where such a difference is eliminated, and the constraint about intermediaries not looking inside the token is nonetheless preserved.

**Comment by dickhardt** [comment]
The use case I was presenting was when a web page is NOT an intermediary -- but a consumer of the ID Token.

**Comment by vibronet** [comment]
The user agent is an intermediary - the fact that the web page executes in the browser's rendering and execution engine doesn't make them the same entity, in the same way in which the cloud fabric or the VM/web server on which a backend runs is not the same entity as the code executing on it. That's infrastructure that might have physical access to code and traffic, but isn't supposed to interfere. And if it does, I bet a lot of people will choose a different provider.
