### ISSUE TITLE
Clear description of HTTP "Accept" Request Header

### ISSUE THREAD

**Issue by ritou** [fedidcg/FedCM#252]
Please define more explicitly that "application/json" be specified in requests to the various FedCM endpoints.

(The current sample code does so, but on 2022/04/15, Chrome Canary appears to be giving the "application/x-www-form-urlencoded" value to requests. This affects the IdP implementation).

**Comment by cbiesinger** [comment]
Hmm yeah that is a Chrome bug. Apologies that I did not see this earlier.

**Comment by cbiesinger** [comment]
The Chrome bug is now fixed but I'll keep this open in case we want to talk more about this in the spec (cc @npm1 )

**Comment by ritou** [comment]
Thanks.
I have confirmed that the correct Header is sent with Chrome Canary.
