### ISSUE TITLE
Recommend not using the term id_token

### ISSUE THREAD

**Issue by gffletch** [fedidcg/FedCM#254]
Given this protocol is unrelated to OpenID Connect which defines id_token it probably makes sense to use a different name for the token identifying the signed in state of the user. I'm not sure referencing the OpenID Connect spec makes sense because that id_token has many capabilities that aren't supported by FedCM.

**Comment by timcappalli** [comment]
I think if it is an OIDC compliant ID token, maybe the name can be `oidc_id_token`. Anything else, I agree, should not use `id_token`.

**Comment by gffletch** [comment]
I'd be ok with `oidc_id_token` but I'm not sure how FedCM allows for things like `acr_values` so I worry about using the name when the protocol only partially supports the OIDC features.

**Comment by timcappalli** [comment]
FedCM cannot introspect the token and doesn't need to understand its contents. They are only passing it on to the RP.

**Comment by npm1** [comment]
I believe we are open to new names - suggestions welcome! That said, it does seem like there are potentially similarities with OIDC's ID token, so I don't think having a shared name is too bad. Thoughts on naming?

**Comment by gffletch** [comment]
For me the concerns here are in regard to what the IDP is required to do. This is a brand new identity protocol and it should be clear what is be required for the flow. If the requirements are for the IDP to comply with the id_token specification as identified in Section 2 of the OpenID Connect Core specification, then `oidc_id_token` makes sense. If the protocol is only defining that the IDP must generate some token related to the identity of the user who authenticated then a new token name should be chosen. Something like `id_assertion` might suffice?

**Comment by gffletch** [comment]
@timcappalli I don't understand the comment "FedCM cannot introspect the token" as OIDC id_tokens are most generally just signed and the signing key is public and discoverable via the openid-configuration document. If the id_token is encrypted for the RP then it's true the browser can not determine the contents. Is that the expectation of the FedCM protocol? All id_tokens returned from the IDP SHOULD be encrypted for the RP?

**Comment by timcappalli** [comment]
Sorry, cannot was probably not the best word. The audience of the token is not the browser so the browser should never be actively parsing its contents.

**Comment by brockallen** [comment]
The id_token is really just the signed OIDC protocol response and doesn't necessarily contains all the identity data being shared with the client/RP.

**Comment by gffletch** [comment]
I think we need to be really careful here… id_tokens in OIDC can easily (and intentionally) contain user data attributes. It all depends on how the request is generated by the RP to the OP. Note also that the “token response” from the OIDC /token endpoint also contains access_tokens which I’m not sure FedCM is supporting in the authentication flow. So I think what is really being returned is an JWT that contains similar claims to the OIDC id_token. Hence I worry that people familiar with OIDC will assume there is more functionality in the id_token than is really supported in the FedCM “id_token” response.

**Comment by ritou** [comment]
If FedCM is envisioning support for various Id Federation protocols, the endpoints and parameter names should be more generic, and the structure of API calls and API responses from the RP should be more flexible.

First of all, we think it should be clear whether FedCM is a shortcut to existing federation protocol flows or a new one similar to them.
If the former, the OIDC IdP should return an IDToken and the SAML IdP would be an Assertion.

If the OIDC IdP considers FedCM, then a request to the current id_token_endpoint would be treated as an extended authentication request such as.

* prompt=none
* response_type=id_token
* response_mode=json <- new!

OIDC IdP will accept other parameters such as scope, and it will not be too difficult to return an IDToken that is compliant with the specification.

**Comment by samuelgoto** [comment]
> If FedCM is envisioning support for various Id Federation protocols, the endpoints and parameter names should be more generic, and the structure of API calls and API responses from the RP should be more flexible.

Yeah, one of the canonical examples is that FedCM needs to somehow work with SAML too (e.g. FedCM needs to enable SAML to do their global logout).

I generally agree that `id_token` isn't the right choice, also because FedCM needs also to support somehow IDPs to pass access tokens back.

> endpoint also contains access_tokens which I’m not sure FedCM is supporting in the authentication flow. 

I'm inclined to use something generic like `token_endpoint` (or `login_endpoint`, to go along with the `login()` JS call that ultimately invokes this HTTP endpoint) that the IDP can use to return "something" (e.g. an idtoken, an access token or a SAML-something) to the RP.

**Comment by samuelgoto** [comment]
> I'm inclined to use something generic like token_endpoint (or login_endpoint, to go along with the login() JS call that ultimately invokes this HTTP endpoint) that the IDP can use to return "something" (e.g. an idtoken, an access token or a SAML-something) to the RP.

Ok, I haven't heard anyone disagreeing with `token_endpoint`, so I'm going to send a PR to change its name and the implementation, to acknowledge that this can be used outside of OIDC.

**Comment by bc-pi** [comment]
`token_endpoint` is already a well known thing in OIDC/OAuth and using the same name for something different in FedCM seems likely to cause confusion. 

https://datatracker.ietf.org/doc/html/rfc6749#section-3.2
https://openid.net/specs/openid-connect-core-1_0.html#TokenEndpoint
https://datatracker.ietf.org/doc/html/rfc8414#section-2
https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata

**Comment by npm1** [comment]
What about just `token` or something a bit different like `id_response`?

**Comment by samuelgoto** [comment]
I don't feel too strongly about the name ... and generally agree that if we can easily avoid the conflict we should ...

**Comment by tttzach** [comment]
Let's go with `token`?

**Comment by npm1** [comment]
We'd like to reach covergence on this soon. How about this:
* Rename [id_token](https://fedidcg.github.io/FedCM/#dom-id_token_endpoint_response-id_token) to `token` to prevent conflict with existing names
* Keep [id_token_endpoint](https://fedidcg.github.io/FedCM/#dom-manifest-id_token_endpoint) as-is because `token_endpoint` would conflict with existing names

If there's no objections, I will send a PR!

**Comment by samuelgoto** [comment]
Ha, I think I prematurely closed this issue here. The PR that was merged names the *response* from `id_token` to `token`, but it did not rename the endpoint from `id_token_endpoint` to `token_endpoint`.

Let me re-open this to try to resolve it.

**Comment by npm1** [comment]
Reopening for realsies since I believe you meant to do that.

**Comment by samuelgoto** [comment]
Based on the suggestion from @gffletch:

> Something like id_assertion might suffice?

and the observation by @ritou: 

> If the former, the OIDC IdP should return an IDToken and the SAML IdP would be an Assertion.

I think something like `id_assertion_endpoint` or `assertion_endpoint` could work.

I'm planning to send a PR to rename the `id_token_endpoint` to one of these options soon to resolve this issue, LMK if you find any other problems.

**Comment by npm1** [comment]
Assertion by itself seems a bit unclear to me. What is it asserting? `id_assertion` as suggested earlier might be slightly better. I don't think I understand why it is an assertion though. Another idea: would `identity_token` be different enough to qualm the concerns about conflicts with other naming?

**Comment by samuelgoto** [comment]
`id_assertion` works for me. I'll update my PR.

**Comment by samuelgoto** [comment]
The PR was merged:

https://github.com/fedidcg/FedCM/pull/329

> Something like `id_assertion` might suffice?

@gffletch 's suggestion is what we ended up with.
