### ISSUE TITLE
Why is fedcm.json hardcoded?

### ISSUE THREAD

**Issue by annevk** [fedidcg/FedCM#259]
Hardcoding paths is not very web-like.

**Comment by matthewp** [comment]
Which part of the hardcoding do you mean? Surely there's quite a bit of hardcoding on the web; `robots.txt`, `favicon.ico` come to mind. Well-knowns are another common type of hardcoding. Is there another approach you would prefer here?

**Comment by annevk** [comment]
`.well-known/` would be acceptable. Advertising the location in some way would also be acceptable. `robots.txt` is not precedent we want to follow.

**Comment by samuelgoto** [comment]
> I personally would be fine with letting IDPs specify the full path (this would make WPT tests a little easier too)

That works for me too. I'll send a PR to make that change.

@annevk LMK if that doesn't work for you.

**Comment by samuelgoto** [comment]
> That works for me too. I'll send a PR to make that change.

https://github.com/fedidcg/FedCM/pull/278/files

**Comment by annevk** [comment]
Thanks, that works for me. Hard-coding paths outside `.well-known` is not something we should do in new features.

**Comment by samuelgoto** [comment]
PR merged, closing this issue. 

@cbiesinger LMK If I didn't get the PR quite right, but otherwise I got @npm1's review.
