### ISSUE TITLE
Specify what 'approved_clients' is used for

### ISSUE THREAD

**Issue by npm1** [fedidcg/FedCM#263]

**Comment by samuelgoto** [comment]
Ah, yes, good point. Totally missing in the spec. Want to send a PR?

**Comment by samuelgoto** [comment]
Ah, actually, let me pick this up so that I can resolve this too:

https://github.com/fedidcg/FedCM/issues/247

PR on its way.

**Comment by samuelgoto** [comment]
PR sent:

https://github.com/fedidcg/FedCM/pull/270

**Comment by cbiesinger** [comment]
I guess this can be marked fixed now that the PR is merged? Though see my comment in that PR

**Comment by samuelgoto** [comment]
> I guess this can be marked fixed now that the PR is merged? 

Ah, yes, I'm going to resolve that.

> Though see my comment in that PR

Your comment is a valid one that I'll follow up on a separate PR. It is an algorithm change though, not affecting what it is intended to use for, so I'll resolve this for now.
