### ISSUE TITLE
OT - Breaking Changes von 101 to 102?

### ISSUE THREAD

**Issue by asr-enid** [fedidcg/FedCM#265]
Its seems there are breaking changes from OT 101 to 102? My prototype IDP implementation work fine with Chrome 101 and fails with 102 after fetching IDP metadata

'The provider's FedCM manifest list file fetch resulted in an error response code'

The endpoint returns:

`
GET /fedcm.json 200 
{"accounts_endpoint":"/fedcm/accounts_endpoint","client_metadata_endpoint":"/fedcm/client_metadata_endpoint","id_token_endpoint":"/fedcm/token_endpoint","revocation_endpoint":"/fedcm/revocation_endpoint","branding":{"background_color":"rgb(118, 184, 42)","color":"0xffffff","icons":[{"url":"https://xxxx/images/netid-round-green.ico","size":32}]}}`

**Comment by yi-gu** [comment]
Sorry for the breaking change we made!
In M102 we enforced a new [top level domain manifest](https://developer.chrome.com/blog/fedcm-origin-trial/#top-level-domain-manifest) to prevent [trackers from abusing the API](https://github.com/fedidcg/FedCM/issues/230).

**Comment by asr-enid** [comment]
I added that actually, but never get to the point this is even fetched (Chrome fails with the above error, never tries to fetch another endpoint)

**Comment by asr-enid** [comment]
Sorry got it - it needs to be served from the eTLD+1 directly. Thats causing this issue then!
