### ISSUE TITLE
UX Affordance for the user to Sign-in to the IDP

### ISSUE THREAD

**Issue by samuelgoto** [fedidcg/FedCM#283]
> filing this on behalf of feedback we got from developers

The FedCM Account chooser today doesn't show any UX when the user is logged into the IDP (e.g. when the IDP returns an empty `[]` array for the `accounts_endpoint`).

While that's a valid UX pattern, there are a number of cases that we want to cover when the user is **not** logged in to the IDP.

The most immediate solution that comes to mind is some sort of UX affordance like a webview pop-up window that allows the user to log into the IDP using their own infrastructure (i.e. HTML/JS/CSS). We would probably also want some sort of JS API that allows the IDP to notify the browser to close the popup window and return to the account chooser.

**Comment by obfuscoder** [comment]
I am very much interested in this topic. It would not only allow singing into the IdP, but also registering an account at the IdP. The reason why this is important: People might clear browser data from time to time or setup a new device/browser and will not see their IdP listed  when accessing a RP site before logging into their IdP site.

**Comment by samuelgoto** [comment]
I'm going to mark this as a duplicate of issue https://github.com/fedidcg/FedCM/issues/442 and we can go from there.
