### ISSUE TITLE
[Editorial] IdentityCredential methods should throw errors, not return them

### ISSUE THREAD

**Issue by nsatragno** [fedidcg/FedCM#295]
`IdentityCredential`'s methods should throw errors, not return them.'

[DiscoverFromExternalSource](https://fedidcg.github.io/FedCM/#browser-api-rp-sign-in) should throw exceptions / errors instead of returning them. We somewhat recently changed this here https://github.com/w3c/webappsec-credential-management/pull/196 to better support `AbortController`'s reason.

**Comment by npm1** [comment]
Looks like most of failure modes are currently being thrown as NetworkErrors. Addressed that in PR
