### ISSUE TITLE
[Editorial] Request consent algorithm should return whether consent was granted or not

### ISSUE THREAD

**Issue by nsatragno** [fedidcg/FedCM#296]
[The `request consent` algorithm](https://fedidcg.github.io/FedCM/#request-consent) should return `true` if consent was given or `false` otherwise, and the value should be checked on step 6 of DiscoverFromExternalSource. Otherwise, if the selected `account` is `null`, the `account state` for (rp, null) is checked, which is undefined. An alternative would be to have the `account state` for (rp, null) defined to "unregistered" and add a note explaining it's ok to return `null` from `request consent`.

**Comment by npm1** [comment]
I think this is fixed in https://github.com/fedidcg/FedCM/pull/304 but I also renaming the `request consent` there as it now does all the work
