### ISSUE TITLE
[Technical] User not having a credential vs user not consenting to have their credential shared trivially distinguishable

### ISSUE THREAD

**Issue by nsatragno** [fedidcg/FedCM#297]
It should not be distinguishable whether a user has a credential with the IDP or not for an RP. However, right now it either is trivially distinguishable or there is some underspecification.

After flattening the DiscoverFromExternalSource steps:

* Let accounts list be the result of running the [fetch the accounts list](https://fedidcg.github.io/FedCM/#fetch-the-accounts-list) algorithm.
* ...
* Display an account chooser
* Let account be an account that the user manually selects from the accounts chooser, or null if no account is selected.
* ...
* If [Account State](https://fedidcg.github.io/FedCM/#dom-statemachine-account-state) is [unregistered](https://fedidcg.github.io/FedCM/#unregistered) then return null.

It's not clear at all what happens if the credential list is empty. If that means that since no account is selected, `null` is returned immediately, then that is trivially indistinguishable from the user not selecting an existing account. This is an undesired privacy leak. Mitigation strategies involve having a timeout (this is probably the best), or if that is not desirable not resolving the promise if there are errors ([which is currently what happens with `conditional` mediation](https://w3c.github.io/webappsec-credential-management/#:~:text=Assert%3A%20result%20is,is%20not%20resolved.))

**Comment by npm1** [comment]
Yea we do have the timer mitigation in our implementation so this is underspecified. I might add some stuff for this on my existing PR (otherwise merge nightmare)
