### ISSUE TITLE
[Editorial] AccountState definition claims something it does not do

### ISSUE THREAD

**Issue by nsatragno** [fedidcg/FedCM#298]
The `AccountState` definition claims

> Account State
> Keeps track of whether the user has registered the account in the [RP](https://fedidcg.github.io/FedCM/#rp) or not. Can be [registered](https://fedidcg.github.io/FedCM/#registered) or [unregistered](https://fedidcg.github.io/FedCM/#unregistered) (by default).

This is clearly wrong, as a browser cannot magically learn that the user has registered an account for the RP in another browser. I found this very confusing while reading through the spec. Something better would be:

> Account State
> Keeps track of whether the user agent is aware that the user has registered an account in the [RP](https://fedidcg.github.io/FedCM/#rp) or not. Can be [registered](https://fedidcg.github.io/FedCM/#registered) or [unregistered](https://fedidcg.github.io/FedCM/#unregistered) (by default).

**Comment by cbiesinger** [comment]
> a browser cannot magically learn that the user has registered an account for the RP in another browser.

Not magically, but through an endpoint ;)
https://fedidcg.github.io/FedCM/#dom-accounts_endpoint_response_accounts-approved_clients
