### ISSUE TITLE
Add an endpoint to receive performance metrics

### ISSUE THREAD

**Issue by npm1** [fedidcg/FedCM#321]
It is useful for the IDP to gather performance data from the FedCM API, but we cannot surface individual numbers for each user for privacy reasons. We can surface aggregated data when the IDP provides an endpoint.

**Comment by kdenhartog** [comment]
What particular metrics are you thinking about here? This seems like it could very easily introduce privacy risks as you mentioned, so I'm wondering what sort of privacy tradeoffs we're willing to accept by allowing the IDP to gain access to this information from the browser.

**Comment by npm1** [comment]
Hey thanks for the question! We're still polishing the details but @yi-gu might share something next week.

**Comment by npm1** [comment]
I'm going to close this since Yi opened a separate issue on https://github.com/fedidcg/FedCM/issues/352
