### ISSUE TITLE
Relax the number of providers in the .well-known file to 5-10

### ISSUE THREAD

**Issue by samuelgoto** [fedidcg/FedCM#333]
We kept it at 1 to avoid a tracking attack, and we've always assumed that we would be able to extend it to a handful of URLs (but not arbitrarily).

We got feedback from Identity Providers that it would be constructive to relax it to 5-10 to allow them to represent different development servers, like qa, staging, canaries, etc.

**Comment by jameshartig** [comment]
In additional to development environments there are also different regions that might need to be listed like `eu.idp.com` or `us.idp.com` if an IdP has customers segmented to different regions.

**Comment by samuelgoto** [comment]
> I'm implementing the FedCM API, but after releasing it to production, I'm having trouble verifying it in the dev environment.

Can you point me to your production environment? What's a configURL that I could use?

**Comment by cbiesinger** [comment]
If this is for testing purposes only, you can turn on chrome://flags/#fedcm-without-well-known-enforcement

**Comment by samuelgoto** [comment]
> If this is for testing purposes only, you can turn on chrome://flags/#fedcm-without-well-known-enforcement

There are a couple more things that we are actively working on that may help here:

1) We are exploring bypassing the .well-known check if the RP and the IdP are inside the same eTLD+1. So, if you could have all your RPs under `dev-rp.idp.example` then we would skip the check if it was pointing to `idp.example`.
2) We are exploring offering an alternate .well-known check that allows multiple `configURLs` to exist if they all share the same `accounts_endpoint`. In this formulation, the .well-known file would announce an `acccounts_endpoint` as an attribute that, when available, would skip the check for the `provider_urls`.

@solatsuta any chance (1) or (2) or the chrome://flag that @cbiesinger mentioned above would help you with your problem?

**Comment by npm1** [comment]
So to clarify, you have multiple IDPs under the same eTLD+1? Or just multiple environments of the same IDP?

**Comment by npm1** [comment]
Oh ok. So why do those environments have different account endpoints? I would imagine a user only has to sign in once to be able to access two of these environments?

**Comment by npm1** [comment]
Ok, thanks for clarifying! I don't have any good idea other than relaxing the number per the title of the issue. But that is going to be a tradeoff with privacy as it allows IDPs to add some entropy before the user has gone through the FedCM flow.

**Comment by cbiesinger** [comment]
It sounds like dev and sandbox could probably use chrome://flags, but yes, if there's multiple production IDPs that's problematic. We are hesitant to increase the number of providers due to privacy concerns, as npm says...

**Comment by samuelgoto** [comment]
I'd like to explore this option bit further.

> We are exploring bypassing the .well-known check if the RP and the IdP are inside the same eTLD+1. So, if you could have all your RPs under dev-rp.idp.example then we would skip the check if it was pointing to idp.example.

You say:

> (1): it is difficult to make the RP belong to the same eTLD+1 as the IdP.
>The RP is a different company/organization than the IdP we manage. It would be practically impossible to put them under the > same domain.

And then:

> idp.example.com <-> prod-DB
> dev-idp.example.com <-> test-DB
> sandbox-idp.example.com <-> sandbox-DB
> stg-idp.example.com <-> prod-DB

These are all test environments, right? Are they publicly accessible? Why would they be exposed externally to external RPs? Are you saying that there are RPs, outside of the IdP's eTLD+1, that you'd like to be able to test against your test environments?

**Comment by samuelgoto** [comment]
> sandbox-idp.example.com is not open to the public, but is open to RP.

What does it mean to not be "open to the public" but "open to RP"? Aren't external RPs "public"?

Do you mean "open to the public but there is an RP allowlist"?

**Comment by samuelgoto** [comment]
> The environment is open to the public on the Internet, but only developers registered on my platform can access it.

Got it. So, yeah, at this moment, I think the only solution that would work for you is asking all of your RPs to turn on this flag `chrome://flags/#fedcm-without-well-known-enforcement` in chrome while using your development environment.

Would that work? Or would that be too painful?

**Comment by samuelgoto** [comment]
Another option that occurred to me was to having the IdP opt-inot "caching" the accounts endpoint value by using the [IdP Sign-in Status API](https://github.com/fedidcg/FedCM/blob/main/proposals/idp-sign-in-status-api.md). That way, FedCM wouldn't have to hit the `accounts_endpoint` during the `get()` and also wouldn't have to check for the `well-known` file at all.

Caching the "accounts_endpoint" has some problems (e.g. fresheness), but I bet it would like do for, at least, testing purposes.

WDYT?

**Comment by npm1** [comment]
That probably does not work, even for testing. The devs could test the sandbox env but then the prod environment (or really any other) would be broken.

**Comment by samuelgoto** [comment]
> That probably does not work, even for testing. The devs could test the sandbox env but then the prod environment (or really any other) would be broken.

The RPs would be pointing to either the dev/prod environment in the `configURL`, so both would work (e.g. dev would use the cached results and the prod environment would load dynamically).

**Comment by npm1** [comment]
> > That probably does not work, even for testing. The devs could test the sandbox env but then the prod environment (or really any other) would be broken.
> 
> The RPs would be pointing to either the dev/prod environment in the `configURL`, so both would work (e.g. dev would use the cached results and the prod environment would load dynamically).

Not sure I follow, but I guess you mean caching the accounts (on a per-origin basis also?), not caching the accounts endpoint.

**Comment by samuelgoto** [comment]
> Not sure I follow, but I guess you mean caching the accounts (on a per-origin basis also?), not caching the accounts endpoint.

Yes.

**Comment by cbiesinger** [comment]
? We have previously concluded that caching the account list is not workable.

**Comment by samuelgoto** [comment]
I'm now sure that was concluded. I certainly don't think it is true for every IdPs or for every test environments.

**Comment by cbiesinger** [comment]
See #552 for a proposal that helps for use cases that can reuse the accounts endpoint

**Comment by samuelgoto** [comment]
> See https://github.com/fedidcg/FedCM/issues/552 for a proposal that helps for use cases that can reuse the accounts endpoint

I feel that issue is now resolved with the latest proposal #552 , which would allow us to have an arbitrary number of `configURLs`. It does limit the `accounts_endpoint` to be only one per .well-known file, but we can try to relax that once we get there.

Closing, feel free to reopen if you fee like there is something else that we need to address.

**Comment by wseltzer** [comment]
noted [16 June](https://github.com/w3c-fedid/meetings/blob/main/2026/2026-06-16-FedCM-notes.md#httpsgithubcomw3c-fedidfedcmissues827)
