### ISSUE TITLE
Replace Sec-FedCM-CSRF with Sec-Fetch-Dest

### ISSUE THREAD

**Issue by cbiesinger** [fedidcg/FedCM#353]
Instead of introducing a new header Sec-FedCM-CSRF, I propose that we instead use the existing `Sec-Fetch-Dest` header with a new value `web-identity`, matching the root manifest's filename (.well-known/web-identity, https://fedidcg.github.io/FedCM/#check-the-root-manifest)

@bvandersloot-mozilla fyi

**Comment by annevk** [comment]
I hope this is now considered resolved? (Though using "webidentity" sans hyphen.)

**Comment by cbiesinger** [comment]
Yes thanks! https://fedidcg.github.io/FedCM/ does set the destination to webidentity thanks to npm.
