### ISSUE TITLE
logoutRPs needs some polish/consistency

### ISSUE THREAD

**Issue by bvandersloot-mozilla** [fedidcg/FedCM#373]
- Steps 3-11 should be substeps of Step 2. This is the loop per argument.
- The spec indicates that the logout requests are POST in Section 7.4.1 but GET in Section 6.1.
- The logoutRPs algorithm should also have Fetch integration

**Comment by samuelgoto** [comment]
Logout should be GETs, because they need to be backwards incompatible.

**Comment by npm1** [comment]
Thanks for catching! Sent you a PR!

**Comment by samuelgoto** [comment]
Merged, thanks!!

**Comment by samuelgoto** [comment]
Ah, Ben, one thing I didn't mention: chrome has implemented logoutRPs but
we haven't shipped that yet. We are waiting for a developer that can test
it with us and give us guidance if the API shape works for them.

So, if Firefox implements it too, I'd put it behind a flag until we
collectively gather more confidence in it.
