### ISSUE TITLE
Make explicit that there can be multiple state machine keys for a particular RP

### ISSUE THREAD

**Issue by judielaine** [fedidcg/FedCM#388]
While this may be "obvious"  i suggest an explicit statement that prevents differing interpretations in the future. 

I suggest text along the lines of:

> The state machine must allow multiple keys with a state of "registered" for a particular RP. 

There are many usecases where an individual may use (register) multiple IdPs with a single RP: 

* a contractor that needs to use an application like WorkDay or Service Now authenticating using enterprise IdPs for multiple contracts
* a doctor with assignments in multiple medical groups who needs to authenticate to a particular health care portals with the different professional relationships
* a researcher with affiliation to multiple libraries, where the libraries offer different resources at a particular journal publisher
* a scholar with multiple  adjunct faculty appointments that give differing access to a learning portal.
* an individual may have different personas at a particular IdP and use more than one of those persona at an RP.

Note that this is not exactly like https://github.com/fedidcg/FedCM/issues/319 which appears to focus on the RP indicating multiple IdPs are acceptable. This follows on that issue by clarifying that given a set of IdPs accepted by an RP, a end user may use more than one and should NOT be required to "deregister" an IdP relationship with an RP before registering a second IdP with that RP.

**Comment by npm1** [comment]
The keys in the state machine are already a triple `(rp, idp, account)`. I dont think this needs to be explicit? Is there a reason you think so? It is also up to the RP and IDP how/if they allow users to perform multiple logins at the same time, not up to the browser.

**Comment by judielaine** [comment]
I will admit my concern is informed with working with UX teams and assumptions that can be made. I felt the explicit part was more to communicate to a non-implementer that there should be more than one allowed IdP per RP (as well as more than one allowed account per IdP per RP). I am unfamiliar with W3C spec conventions: perhaps my concern is better supported in other documentation.

**Comment by npm1** [comment]
After writing the PR for this issue, I'm not really convinced that we need a note. It should be clear that a user may have more than one 'registered' account from the shape of the state machine. So I think we should close this issue, is that reasonable to you?

**Comment by judielaine** [comment]
Yes, my regrets for causing churn.
