### ISSUE TITLE
HOWTO is out of date compared to the spec?

### ISSUE THREAD

**Issue by philsmart** [fedidcg/FedCM#392]
I think https://github.com/fedidcg/FedCM/blob/main/explorations/HOWTO.md is out of date compared to the spec. Specifically around the IdentityProviderAPIConfig object returned from /fedcm.json. e.g. id_token_endpoint is now id_assertion_endpoint.

**Comment by npm1** [comment]
Good catch!

**Comment by philsmart** [comment]
Also, the fedcm.json example response contains id_token instead of the id_assertion_endpoint. And the example JS credentials API call uses the wrong object parameters e.g. `federated` instead of `providers` etc.

Probably some of it has just drifted slightly given the spec is evolving.

**Comment by npm1** [comment]
Ah yes, updated the PR to include that too
