### ISSUE TITLE
web-identity file HTTP response does not require an application/json Content-Type

### ISSUE THREAD

**Issue by philsmart** [fedidcg/FedCM#409]
This a minor point, as I am sure the FedCM API is only expecting a JSON response, but the API does not seem to care if GETing the .well-known/web-identity file includes an application/json Content-Type response header. It works fine if there is no Content-Type header.

**Comment by philsmart** [comment]
It does not read any Content-Type. I sent `text/xml` for the json response and it worked. Like a say, probably a small thing.

**Comment by npm1** [comment]
Are you asking about the Chrome implementation mismatching something in the spec? Just want to clarify what the issue is

**Comment by philsmart** [comment]
Ah, my fault. Yes, the API in Chrome Canary Version 111.0.5559.0 (Official Build) canary (arm64). My assumption would be, it would check the response is a JSON MIME Type. There is some references to this in the spec. put possibly for the assertions API only: https://fedidcg.github.io/FedCM/#browser-api-rp-sign-in

> If mimeType is failure or is not a [JSON MIME Type](https://mimesniff.spec.whatwg.org/#json-mime-type), throw a new "[NetworkError](https://webidl.spec.whatwg.org/#networkerror)" [DOMException](https://webidl.spec.whatwg.org/#idl-DOMException).
