### ISSUE TITLE
Leverage the common DID URI scheme and data format for IDs, ID resolution flows, and ID metadata/PKI responses

### ISSUE THREAD

**Issue by timcappalli** [fedidcg/FedCM#47]
The DID URI scheme and data format ([Decentralized Identifiers (DIDs) v1.0 (w3c.github.io)](https://w3c.github.io/did-core/)) support all the same flows being represented in the WebID proposal. 

In order to support all types of IDs that can be exchanged between parties, we should align ID URIs and their generation/resolution/management in accordance with the DID URI scheme and data model. We will need to support truly decentralized DIDs anyway, so the risk of not doing this in a unified way here may require us to implement a different superset of APIs for DIDs, some of which will overlap various functions present in the WebID proposal.

**Comment by samuelgoto** [comment]
This was filed early on and I think it is currently "obsolete": we settled on operating at a layer under this, rather in it, so made everything userland agnostic (DIDs, OIDC, SAML, VCs).

I'm going to mark this as closed, feel free to reopen if you feel there is something that is either actionable or needs to be revisited
