### ISSUE TITLE
Feature request: provide developers more visibility of auto re-authentication

### ISSUE THREAD

**Issue by yi-gu** [fedidcg/FedCM#497]
Auto re-authentication is the [default user mediation behavior](https://w3c.github.io/webappsec-credential-management/#dom-credentialmediationrequirement-optional) in Credential Management API. However, auto re-authentication may be [unavailable](https://fedidcg.github.io/FedCM/#auto-reauthenticated) due to reasons that only the browser knows; when it’s unavailable the user may be prompted to sign in with explicit user mediation which is a flow with different properties.

- From an API caller’s perspective, when they receive an id token, they don’t have visibility over whether it was an outcome of an auto re-authn flow. That makes it hard for them to evaluate the API performance and improve UX accordingly.
- From the IdP’s perspective, they are equally unable to tell whether an auto re-authn occurred or not. Whether an explicit user mediation was involved could help them support more security related features. e.g. some users and/or RPs may prefer a higher security tier which requires explicit user mediation in authentication. If an IdP receives a token request, they could reject it if the user didn’t grant permission in the flow.

Therefore, providing visibility of the auto re-authentication flow would be beneficial to developers.

**Comment by asr-enid** [comment]
@yi-gu  seems this should be a proposal under https://github.com/fedidcg/FedCM/tree/main/proposals ?

**Comment by yi-gu** [comment]
thanks @asr-enid!

To follow up from yesterday's call: while we'd like to keep the new proposals in "Issues" such that it's easier for other folks to comment on, we'd be happy to adapt to find ways to accommodate different cases (e.g. for folks who want to keep track on new proposals).

In the interim, for FedCM changes in Chrome, there's a [newsletter](https://groups.google.com/g/fedcm-developer-newsletter) that one can subscribe to.
