### ISSUE TITLE
if clientId is issued by IdP, then IdP can know which RP attempted to connect

### ISSUE THREAD

**Issue by jasonjiicloud** [fedidcg/FedCM#516]
I read the documentation: https://developer.chrome.com/docs/privacy-sandbox/fedcm-developer-guide/#idp-config-file.

It says the browser fetches the config file without the `Origin` and `Referer` header. This prevents the IdP from learning who made the request and which RP is attempting to connect.

But if `clientId` in `navigator.credentials.get` is issued by IdP to specific RP, then IdP can know which RP made the request.

So `clientId` will leak user privacy, so why do we use it?

I think my understanding is wrong. but where's the wrong?

**Comment by npm1** [comment]
I think you're assuming all the info in `get()` is passed to the config file fetch, which is not the case. The `clientId` is used in the client metadata fetch (where IdP should know the RP who is making the request), but not in the config fetch.

**Comment by jasonjiicloud** [comment]
@npm1, what's the difference? not only the client metadata, but also the assertion request, both of them use `clientId`, so certainly the IdP knows who tried to login, which RP attempted to connect.

@npm1 , please correct me.

**Comment by npm1** [comment]
The client metadata fetch will include the RP but not the user, so the IdP will not know who tried to login at that time. In the ID assertion fetch we do include both the user and the RP: the user has at this point accepted to use some IdP account for federated login in the RP, so it is acceptable for the IdP to know this at that time. Let me know if it makes sense and I can close this issue?

**Comment by jasonjiicloud** [comment]
I'm clear. but what's the significance of not letting the IdP know the `Referer` and `Origin` when fetching config file, the IdP will know when doing ID assertion?

**Comment by jasonjiicloud** [comment]
@yi-gu , I understood most of your point of view.

The IdP can learn a specific user's visit to a specific RP only when user grants permission.  I got it.

But for the config fetch, I don't agree:

You said the IdP could return a malicious URL "https://idp.example/rp-origin/accounts", then the IdP could get the RP information from this URL. But according to the rule, the account assertion does contain "Origin" header, so the IdP doesn't need that malicious URL.

If I have something wrong, please correct me.

Thank you.

**Comment by jasonjiicloud** [comment]
@yi-gu, you're right. I understood it. Really appreciate it. Sorry for taking your time.
