### ISSUE TITLE
getUserInfo returns InvalidStateError when ConfigURL is valid?

### ISSUE THREAD

**Issue by sjud** [fedidcg/FedCM#554]
I'm trying to build a test RP/IDP for current chrome canary  https://github.com/sjud/fedcm-example-rp
I'm running
Version 125.0.6402.0 (Official Build) canary (x86_64)

And I am running into an issue where I am using a valid ConfigURL in my getUserInfo call
```js
IdentityProvider.getUserInfo({
            configUrl: "http://127.0.0.1:3000/idp/config",
            clientId: "my_client_id",
        })
```
I believe it's valid because I have a working navigator.credentials.get() call using it

```js
navigator.credentials.get({
                identity: {
                    context:"continue",
                  providers: [{
                    configURL: "http://127.0.0.1:3000/idp/config",
                    clientId: "my_client_id",
                    nonce: "123",
                  }]
                }
              })
```

My getUserInfo is being called from http://127.0.0.1:3000,
 
I get this errror
```
InvalidStateError : Provider information is incomplete
```

This is after I've logged into the IDP, returned to the site. It's from an iframe with  allow="identity-credentials-get" whose src is "http://127.0.0.1:3000/idp" 

 I am running the IDP and the RP off of the same origin. 
 
Thanks!

**Comment by sjud** [comment]
Nevermind, sorry!

**Comment by samuelgoto** [comment]
Just so that we know (the next person that runs into this knows), any chance you could report back on this thread what resolved this issue? Was there something in the documentation that maybe was too easily to overlook?

**Comment by cbiesinger** [comment]
I suspect the cause was that `configUrl` should be `configURL` in getUserInfo, like in n.c.get()

It is unfortunate that we did not provide a better error message

**Comment by sjud** [comment]
Hi, Sorry I didn't respond to this. Yes you were right. Thanks for improving the error message. :)
