### ISSUE TITLE
How do you see the API per RP working? The API comes from the `fedcm.json` file which is served without credentials and without client_id or referrer information. How does the IDP provide differing RP information to FedCM?

### ISSUE THREAD

**Issue by cklim5** [fedidcg/FedCM#576]
How do you see the API per RP working? The API comes from the `fedcm.json` file which is served without credentials and without client_id or referrer information. How does the IDP provide differing RP information to FedCM?

The second point is an issue we need to work throught.

_Originally posted by @dj2 in https://github.com/fedidcg/FedCM/issues/231#issuecomment-1067011794_

**Comment by timcappalli** [comment]
spam
