### ISSUE TITLE
Reset "Not signed in with the identity provider"

### ISSUE THREAD

**Issue by anderspitman** [fedidcg/FedCM#588]
I've found that if my endpoints return an error (even once apparently), I end up in a state where chrome stops trying to send requests and simply prints the above in the console. The only way I've found to reset this is by removing the chrome cache and config directories and starting from scratch, which is very inconvenient. Is there a quicker way to do this?

**Comment by aaronpk** [comment]
I noticed this too but I'm pretty sure setting the logged-in state resets it.  Either 

```
Set-Login: logged-in
```

or

```
navigator.login.setStatus("logged-in")
```

**Comment by npm1** [comment]
Yea, this is due to the login status API. As Aaron mentions, the fix is to mark the login status in the IDP as logged in again so that Chrome resumes the FedCM fetches for that IDP. I think we can close this one?

**Comment by anderspitman** [comment]
Setting `Set-Login` seems to be letting me get back to a good state. Thanks!
