### ISSUE TITLE
Bug - FedCM shows only 1st account after login

### ISSUE THREAD

**Issue by yaron-zehavi** [fedidcg/FedCM#597]
Chrome Version 125.0.6422.77 (Official Build) (64-bit)
---
After IDP accounts endpoint returns HTTP 401, user is prompted to login.
**After completion of login** accounts endpoint returns 2 accounts, but FedCM displays only the first account.
When refreshing the page FedCM displays both accounts.
When IDP changes the order of accounts returned FedCM displays still a single account, the first instance in accounts endpoint response.

![Fedcm after login showing only one account - changed order](https://github.com/fedidcg/FedCM/assets/159145437/b9d3ac56-7c00-4f4f-9b8c-16d0bc721933)
[accounts response.txt](https://github.com/fedidcg/FedCM/files/15400292/accounts.response.txt)
![Fedcm after refresh showing both accounts](https://github.com/fedidcg/FedCM/assets/159145437/9ab7952c-624e-4881-921d-892dc3fef437)
![Fedcm after login showing only one account](https://github.com/fedidcg/FedCM/assets/159145437/536b0635-c35d-4594-aecb-b25fda9e6331)
![Fedcm before login](https://github.com/fedidcg/FedCM/assets/159145437/3aa018ee-0f46-4d6d-b766-8d5de7f36e07)

**Comment by anderspitman** [comment]
@yi-gu [LastLogin](https://lastlogin.io/) works exactly the way you describe; you can log in to multiple identities during a single LastLogin login.

**Comment by yaron-zehavi** [comment]
I understand the logic, thanks

**Comment by yi-gu** [comment]
> @yi-gu [LastLogin](https://lastlogin.io/) works exactly the way you describe; you can log in to multiple identities during a single LastLogin login.

Thanks for letting us know. Will track the change in https://issues.chromium.org/u/1/issues/342194490

**Comment by anderspitman** [comment]
Thanks @yi-gu. I'm open to designing around this if necessary, since it is a pretty niche use case.
