### ISSUE TITLE
Logout considerations

### ISSUE THREAD

**Issue by kenrb** [fedidcg/FedCM#62]
I am creating this issue mostly because a discussion in this area would be helpful.

@samuelgoto has added [a proposal](https://github.com/WICG/WebID/blob/main/cookies.md#logout) to try to offer a path forward for [front-channel logout](https://openid.net/specs/openid-connect-frontchannel-1_0.html) use cases once third-party cookies are deprecated.

The basic idea is for the browser to infer an identity federation relationship between the RP and the IdP and then allow special credentialed requests from the IdP to the RP based on that. A few questions come out of this, and community feedback would be great.

1. How constrained can the logout URI be and still be useful for IdPs? Can this just be a protocol and host name, or is a path required? (I am guessing a path is needed in most deployments.) If we don't allow query parameters (i.e. `iss` and `sid`, which are optional in the spec), would this still be useful?
2. How much of a problem is it that this is not being done with an iframe? The consequence is that the RP can't return script to do something like clear anything in LocalStorage.
3. Is an API needed for this at all? If the user agent is satisfied that a good faith RP/IdP relationship has been established then why not just relax 3p cookie restrictions for the RP's origin within a page loaded by the IdP?
4. As @samuelgoto mentions, the means of establishing that relationship is an open question. He provides a couple of rough ideas but we haven't gone very far yet in assessing feasibility, use case coverage, and abuse resistance attached to them.

**Comment by samuelgoto** [comment]
> @samuelgoto has added [a proposal](https://github.com/WICG/WebID/blob/main/cookies.md#logout) to try to offer a path forward for [front-channel logout](https://openid.net/specs/openid-connect-frontchannel-1_0.html) use cases once third-party cookies are deprecated.

Since this was filled, we implemented a prototype in chrome canaries that no developer used, so we removed the feature and the spec consideration.

It is possible that we'll revisit this in the future, but I think that the spec evolved a lot since this was initially considered, so much so that it is worth revisiting from first principles.

So, I'm going to mark as this as obsolete, since we no longer have the ability to `logoutRPs()` in the spec.
