### ISSUE TITLE
Label numbers mixed up in delegation-oriented model diagram

### ISSUE THREAD

**Issue by johnwilander** [fedidcg/FedCM#68]
The delegation-oriented model diagram has multiple issues with numbered labels. First, 3 is missing. Second, 5 is missing too. Finally, it has 6, 6a, and 6c, but no 6b.

**Comment by samuelgoto** [comment]
> The delegation-oriented model diagram has multiple issues with numbered labels. First, 3 is missing. Second, 5 is missing too. Finally, it has 6, 6a, and 6c, but no 6b.

Since this was filled many years ago, we ended up nor pursuing the delegation-oriented model, because that would be backwards incompatible.

I'm going to mark this as obsolete, feel free to re-open if you'd like more clarification.
