### ISSUE TITLE
Intriguing and familiar territory about Federated ID

### ISSUE THREAD

**Issue by teamktown** [fedidcg/FedCM#7]
Hi.
The feedback link led me here. There is a lot of prior work here that exists globally and want to highlight it to help inform and explore intersections with you. 
I work at an organization that operates the [Canadian Research and Education(R&E) federation](https://www.canarie.ca/identity/). R&E is not one jurisdiction but a global activity and we participate in operating a global R&E community exchange point called [eduGAIN spanning 68 countries](https://technical.edugain.org/status).  The R&E identity ecosystem and has 1000's of entities with around ~3,600 IdPs and ~2,900 Relying Parties. Foundation protocols are SAML based and you can see this at our public metadata exchange nexus at https://technical.edugain.org

Many of the topics being explored in webID are viscerally experienced by us having operated for over a decade. Our community of identity practitioners (IdP, RP, and Federation Operators) have acrued over a decade of experience and with the work in WebID I think there's some interesting opportunities to exchange thoughts and insight on your work.

Some are:
- The discovery/nascar challenge:  Recent works like https://seamlessaccess.org and https://eduteams.org are recent activities augmented existing practices.  There are others, but this is a somewhat solved area or known challenge that has been largely worked on.
- Scaling trust beyond SAML:  The trust model in SAML affords many things but not all services implement well.  We are also working on bringing the federation model to OIDC with  [federation profile work there](https://openid.net/wg/rande/) thus leveraging OIDC infrastructure to carry additional trust
- Privacy: This is a core operational tenant in the R&E space and is manifest in many places both operationally and in policies too numerous to list and happy to discuss.

It would be interesting to understand how R&E federation does or does not address what is proposed with WebID as I think there's a lot we address. Thoughts welcome on this.

**Comment by npm1** [comment]
Hey, just seeing this. If still interesting in sharing ideas, let us know!

**Comment by samuelgoto** [comment]
Hey @teamktown this totally fell through the cracks, and I'm sorry that we missed it :( Is your offer still standing? If so, we are very interested in learning more from you!

Our chair @hlflanagan is super involved in a lot of the EDU space and has introduced us to a series of groups, like the SeamlessAccess group and european IDPs, like Daasi and the Shibboleth community.

Any chance you would be interested in dialing into one of the FedID CG meetings someday?

**Comment by teamktown** [comment]
Hi @samuelgoto, Yes, the offer still stands and will connect with @hlflanagan on it.

**Comment by teamktown** [comment]
@teamktown and @hlflanagan talked about how to attract more people to actively engage in testing the FedCM API. More to come and we’d like to keep the issue open to make sure we come back to where and how R&E should engage in this effort.

**Comment by samuelgoto** [comment]
> Hi @samuelgoto, Yes, the offer still stands and will connect with @hlflanagan on it.
> @teamktown and @hlflanagan talked about how to attract more people to actively engage in testing the FedCM API. 

I think the original intent of this issue is resolved, since our communities are fairly connected now, many thanks to @hlflanagan and @teamktown and @philsmart and @judielaine and @nckroy and the various summits / community calls that are ongoing.

The job isn't done and there is a lot of open questions (and much of it was broken down into smaller parts), but I think that now we have everybody talking to everybody.

I'm going to mark this as closed, since I think we accomplished the goal here of approximating the communities. 

Feel free to re-open if you feel like there is something else actionable here.
