### ISSUE TITLE
Directed Basic Profile Optional Fields

### ISSUE THREAD

**Issue by jameshartig** [fedidcg/FedCM#72]
It's not clear if all of the fields in the [Directed Basic Profile](https://github.com/WICG/WebID/blob/main/directed_basic_profile.md) are actually required? In particular I could see email and email_verified being optional as there's already precedent from IDPs that the user might turn off the sharing of their email. In some cases that means that a proxy email is shared instead but the spec isn't clear if you can send no email or an empty email when sharing was not authorized.

**Comment by cbiesinger** [comment]
I believe this issue was for an early version of fedcm; we now treat the token as an opaque string so this is not an issue anymore.
