### ISSUE TITLE
Offline capabilities

### ISSUE THREAD

**Issue by EtienneBruines** [fedidcg/FedCM#74]
## Background

The README and the [HOWTO](https://github.com/WICG/WebID/blob/main/HOWTO.md#permission-oriented-variation-protocol-details) describe that the response of `/.well-known/webid` is key in figuring out what will happen:
- the request can error, indicating that WebID is not supported
- the request may return with an `idp_endpoint`
- the request may return with a `token_endpoint`.

Additionally, as part of the [IdP sign-in page](https://github.com/WICG/WebID/blob/main/HOWTO.md#idp-sign-in-page) the browser loads a page of the `idp.example` domain, after fetching the correct URL information. 

---
## Proposal

Allow the service worker of `idp.example` to handle *all* requests that are part of the WebID authentication process, and document that in the spec/explainer.

This specifically includes requests to `/.well-known/webid` (and subsequent requests) that the browser initiates after the Relying Party invokes `navigator.id.get`

---

## Discussion

Since the browser initiates these requests internally, would it be possible for a service worker to handle these requests? ...and possibly responding with a cached response? Specifically the service worker that may (or may not) be registered to the `idp.example` domain and not the `rp.example` domain. 

Ideally, it will end up serving resources for the `Idp sign-in page` later on anyways. 

This would result in a few pros:
- Performance improvements: 
  - The call to `/.well-known/webid` is static anyways and can be pre-cached. <sup>1</sup> 
  - The subsequent call to `https://idp.example/webid/signin?{OAuth request string}` might also be cached.<sup>2</sup>
  - The IdP sign-in page will hopefully be served from the service worker anyways.<sup>1</sup>
- Offline-support possibilities:
  - Especially for use-cases where the Relying Party only needs to know *"can I trust this email address?"* the `idp.example` domain could completely respond without any network response. Depending on the amount of information the `idp.example` domain has available in e.g. IndexedDB, the service worker could respond with all kinds of niceties as part of the JWT response.
- Allows for more types of credentialed requests than just cookies. This would allow the service worker to set appropriate `Authorization` HTTP headers.

<sup>1</sup> The explainer does not yet spec, whether or not this *can* even be cached -- it makes sense, but it is not specked.
<sup>2</sup> I can imagine use-cases where the OAuth request string contains a JWT from the Identity Provider, vouching that the Relying Party can be trusted; this way the service worker only needs to validate the JWT and can immediately respond with the appropriate URLs. No network required.

Security-considerations: none that I could think of. The service worker is solely part of the `idp.example` domain and would have been registered by previous visits to `idp.example`. Requests would be attributed to the `idp.example`-origin and scope, meaning the service worker can handle it as any request would be.

**Comment by cbiesinger** [comment]
The spec explicitly disables service worker interception. And it is difficult to enable it for privacy reaasons -- service workers could inject the RP identity or other data into the credentialed account list request, and because this happens before explicit user permission is granted, this is not acceptable.

With regards to caching, since the spec just invokes the generic fetch algorithm, this should work as expected.

I am unsure that offline functionality would work well, since in practice the IDP would need to sign an identity assertion and is unlikely to want to have the key stored in a client-side service worker.

I'm closing this for now, but feel free to reopen if you think there is something actionable here.
