### ISSUE TITLE
Mediation oriented API too limited - single token response

### ISSUE THREAD

**Issue by will-bartlett** [fedidcg/FedCM#81]
I was reviewing the mediation-oriented API from WebID as a successor to the permission-oriented API. I work for Microsoft in the Identity space. I observed that the mediation-oriented API is limited to a single id_token response. This choice is strongly out-of-sync with the wider Identity ecosystem - modern authentication protocols like OpenID Connect bundle authentication with authorization obtaining multiple tokens at a time. Consumers of the permission-oriented API will struggle to migrate to the mediation-oriented API if is does not meet the same use cases as the permission-oriented API. See e.g. the [OpenID Connect specification](https://openid.net/specs/openid-connect-core-1_0.html). 

Instead, consider having the API return an object whose .IdToken property is mandatory and contains an IdToken, but can have other properties.

**Comment by cbiesinger** [comment]
We settled on the token being an opaque string, so the IDP can just serialize a JSON object, or format them in any other format that they agree on with the RP.
