### ISSUE TITLE
Mediation oriented API too limited - JWTs

### ISSUE THREAD

**Issue by will-bartlett** [fedidcg/FedCM#82]
I was reviewing the mediation-oriented API from WebID as a successor to the permission-oriented API. I work for Microsoft in the Identity space. I observed that the mediation-oriented API is limited to a JWT response - the explainer for the parameter to `navigator.id.provide` says "The string should contain a JWT." JWTs, while popular, are not universally popular, and do not represent a perfect implementation. Various proposals (e.g. [CBOR](https://www.rfc-editor.org/rfc/rfc8949.html)) address the size aspects of JWTs, trying for smaller tokens. Other proposals try to address some of the complications of the JWT spec - e.g. removing "alg":"none". On the other end of the spectrum, slower moving industries (like education) continue to use SAML tokens (compressed XML instead of JSON). And various proprietary systems (including Microsoft's) use proprietary token formats. Limiting the mediation-oriented API in WebID to JWTs harms these slower moving customers who are still on older technologies and limits evolution in Identity technologies that result in more secure, private, and efficient exchange of Identity information.

If the connection to JWTs is driven by a desire to allow the browser to parse part of the token (e.g. the username), the WebID API should just move the fields that the browser parses outside of the token. In general, if the token is intended for the relying party (the website), the browser should avoid parsing it - this is a general best practice of Identity - don't consume a token if you're not the audience

**Comment by cbiesinger** [comment]
We have settled on the token being an opaque string, which I believe addresses this issue.
https://fedidcg.github.io/FedCM/#idp-api-id-assertion-endpoint:~:text=The%20content%20of%20the%20token%20is%20opaque
