### ISSUE TITLE
Missing Attack Scenario:  IDP and RP owned by the same entity

### ISSUE THREAD

**Issue by kdeqc** [fedidcg/FedCM#85]
I think an Attack Scenario should be included for when the IDP and the RP are owned by the same entity.  It's a subset the IDP and RP colluding together, but I think it should be addressed directly because 1) it may make it that much easier to collude, and 2) theoretically, it's possible that only one party (either the IDP or the RP) could be abusing the trust without the other party's direct involvement.  This might not be something that can realistically be mitigated against, but I think there is still value in identifying those types of situations as well.

**Comment by alextcone** [comment]
This is a very common scenario. At least in the Western Hemisphere, the most scaled IDPs are also RPs (and sell ad tech).

**Comment by samuelgoto** [comment]
When IDPs and RPs are owned by the same entity, we would expect that collusion wouldn't be practical or necessary because they could add themselves to the same [first party set](https://github.com/privacycg/first-party-sets).

Does that make sense?

**Comment by npm1** [comment]
We haven't received a response, and we have updated the privacy and security considerations since then, so I will close this but feel free to comment if you feel something is missing.
