### ISSUE TITLE
Expand on rationale for modal window

### ISSUE THREAD

**Issue by estark37** [fedidcg/FedCM#9]
I wonder if this explainer could expand more on the rationale for using a tab-modal dialog or the modal-window proposal instead of a top-level navigation, new tab, etc. Maybe some of the reasoning is similar to Payment Handlers, but I think it would be good to explain it here too and make sure that all the same reasoning still applies.

The new tab-modal pattern that's used for Payment Handlers is generally a little uncomfortable because it blurs the line between web content and native browser UI -- a line which is already fuzzy and not very well understood by users. Plus, the concept of showing two origins at once in the UI has been proven to be confusing to users in other settings (https://docs.google.com/document/d/1iaocsSuVrU11FFzZwy7EnJNOwxhAHMroWSOEERw5hO0/edit). On mobile in particular the bottom sheet pattern really gives up on the line of death concept (https://textslashplain.com/2017/01/14/the-line-of-death/).

All that to say, it's not obvious to me that it's a good idea to cement the bottom-sheet/tab-modal pattern for hosting arbitrary web content, so I think it deserves some more discussion in the explainer.

**Comment by npm1** [comment]
The API as is right now is mainly focused on capabilities that would break with third party cookie deprecation, which is a reality or happening soon across browsers. The other options you suggest are 1) more intrusive 2) still available after 3PCD. The current explainer does indicate the urgency in https://github.com/fedidcg/FedCM/blob/main/explainer.md#what-will-break. Is it ok to close this?

**Comment by samuelgoto** [comment]
Since this was initially filled, we moved away from the "payment handler"-like UI that @estark37 was referring to, in favor of a "mediated" account chooser UI.

I'm going close this issue and mark it as "obsolete", feel free to re-open if you still feel like there is something actionable to be done.
